name: sensoresapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.1
  floor: ^1.4.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  provider: ^6.1.1
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
   - assets/images/fondo_login.jpg
